[contract]
# The address of the deployed WBI contract
address = "0x1aEe6BAD4e2B3ea2dadF6753dA3d77Da79290c9b"

[account]
# The ethereum address which will create the transactions
# (needs to have a high enough balance)
address = "0xfe1b2865B74200dCEABf9dDEE04FDc32c2C8E3FB"

[witnet_node]
# Address of the JSON-RPC server
jsonrpc_ip = "127.0.0.1"
jsonrpc_port = 1234

